### PR TITLE
Fix inject_test_data.py after changes in Link._submit

### PR DESCRIPTION
**Pull request by eleweek**
Hi, it looks like https://github.com/reddit/reddit/commit/d2127935098024216c780c47145eef60ff0d9212 broke the script. I fixed it, and it now seems to work again!

### CODE REVIEW

**Comment by dwick** [comment]
:+1:

**Comment by dwick** [comment]
6889236

**Comment by dwick** [comment]
@eleweek you can email me at wick@reddit.com with your username if you want a trophy.

**Comment by eleweek** [comment]
Thank you for merging it! I emailed you from avp-13@yandex.ru

**Pull request closed without merging**
