### PR TITLE
Improve approved submitters info page title

### PR DESCRIPTION
**Pull request by angrypotato1**
This is to match this commit: https://github.com/reddit/reddit/commit/d30f04636fbe38cc3e951414bc95544fc2e634a3

Using the same logic as xiang, it makes sense to change the approved contributors menu item.

this page is accessible to non-mods (on private subreddits only iirc), so there may be a difference in reasoning but I feel the change is just as relevant as the linked commit.

### CODE REVIEW

**Comment by xiongchiamiov** [comment]
:eyeglasses: @xiongchiamiov to remind myself to take a look at this.

**Comment by 13steinj** [comment]
@angrypotato1 it looks like this change was made but no one ever closed the PR.

**Comment by angrypotato1** [comment]
@13steinj @xiongchiamiov nope i'm not seeing a change

**Comment by 13steinj** [comment]
@angrypotato1 I just double checked the master, [the change was made](https://github.com/reddit/reddit/blob/master/r2/r2/lib/menus.py#L132)

**Comment by umbrae** [comment]
:fish:

**Comment by Deimos** [comment]
Thanks, merged and deployed: https://github.com/reddit/reddit/commit/7897c2f6b26fd04fdfb33d29f6999c06d3bfd64b

**Pull request closed without merging**
