### PR TITLE
Expose GET_comment_by_id to non admins

### PR DESCRIPTION
**Pull request by 13steinj**
This will allow users to get to a comment via /c/commentid, which could be useful.

Since the same logic to hide private sub's applies as it were in the link id redirect, this also factors that out into a separate function to reduce on repitition.

### CODE REVIEW

**Comment by empyrical** [comment]
would also open up the thing i attempted in #1063

**Comment by 13steinj** [comment]
@empyrical didn't know! sorry to steal the thunder (if that's what I did).

I don't personally agree on the comment shortlinks though, since that's not really something that can be changed from an outsider (in production, they use a specific short domain and they'd need to change that on their end as well)

**Comment by empyrical** [comment]
nah no worries,i closed it because it became unmergable and it needed to be rewritten anyways (its almost 2 years old now lol)

i spoke to them on irc when i made it and they said that they just need to change something in their load balancer to allow `redd.it/c/xxxxx` to work

**Comment by bsimpson63** [comment]
Sorry, but this repository is no longer accepting pull requests.

**Pull request closed without merging**
