### PR TITLE
Added AutoModerator to the config permission tooltip

### PR DESCRIPTION
**Pull request by Jakeable**
The config permission now has the ability to manage AutoModerator, so the tooltip should reflect this.

### CODE REVIEW

**Comment by xiongchiamiov** [comment]
The change itself is simple enough, but as for whether it's correct, probably best to :eyeglasses: @Deimos .  He's a bit occupied at the moment, so it may be a little while before he can pop in.

**Comment by Deimos** [comment]
I think that's probably correct, though it might be a little better to say something more specific like "automoderator configuration". Mods need to have the "wiki" permission to be able to view the automod configuration, and the "config" one to be able to edit it.

**Comment by Jakeable** [comment]
@deimos how does "AutoModerator config" sound? "Configuration" seems really long compared to the rest of the tooltip.

**Comment by Deimos** [comment]
Sure, that should be good.

**Comment by Jakeable** [comment]
Think this one is ready for primetime now?

**Comment by Deimos** [comment]
Looks good to me, I'll get it added in. Thanks. :fish:

**Comment by Deimos** [comment]
And deployed now: https://github.com/reddit/reddit/commit/e772017d2e5f51a55e9fe542b657f97b75233faa

**Comment by Jakeable** [comment]
Thanks! Would it be possible to get the Open Sorcerer? :wink:

**Comment by Deimos** [comment]
Hmm, I'm actually not sure if we give that for text updates or just actual functional code changes. I'll check with some of the others and confirm.

**Pull request closed without merging**
