### PR TITLE
Retain sort parameter for subreddit sticky redirect

### PR DESCRIPTION
**Pull request by nickdevereaux**
Allows /r/example/about/sticky?sort=new to redirect to the permalink URL and pass the sort parameter along instead of stripping it. 

Useful for daily discussion threads with fresh top level comment content

Example gif

### CODE REVIEW

**Comment by nickdevereaux** [comment]
Based admins plz respond

**Comment by quink** [comment]
I, too, am bump.

**Comment by nickdevereaux** [comment]
Synced my fork so now it'll be a clean merge :+1:

**Comment by bsimpson63** [comment]
Thanks, this looks good. Do you mind rebasing on top of current master? I'll get it merged after that.

**Comment by kjoconnor** [comment]
Please go ahead and rebase if you'd still like this merged. Closing for now.

**Pull request closed without merging**
