### PR TITLE
Added several flexbox properties to CSS filter

### PR DESCRIPTION
**Pull request by TheAppleFreak**
When attempting to push a recent commit to my subreddit stylesheet, I noticed that the CSS validator didn't recognize the `justify-content` property for manipulating flexboxes. [After a little research](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Using_CSS_flexible_boxes), I found that the following four flexbox-related properties were missing from the validator:

* `flex-basis`
* `flex-grow`
* `flex-shrink`
* `justify-content`

Adding these properties would make our lives just *that* much nicer.

### CODE REVIEW

**Comment by spladug** [comment]
Thanks! I'll get that merged in and deployed ASAP.

**Comment by TheAppleFreak** [comment]
Thanks! :D

**Comment by spladug** [comment]
Merged as 24c521cff2b99099bb5bbc294c0596983104429e! Thanks for the contribution.

Are you /u/TheAppleFreak on reddit? I'll give you a trophy over there if so.

**Comment by TheAppleFreak** [comment]
That I am.

**Comment by spladug** [comment]
all done, thanks again!

**Pull request closed without merging**
