### PR TITLE
Update authentication.py

### PR DESCRIPTION
**Pull request by grandpaslab**
Add support for automatic account creation when using basic auth.

### CODE REVIEW

**Comment by grandpaslab** [comment]
I'm running a reddit instance on an intranet. My use case requires reddit account creation when user first logs in via basic auth, credentials being maintained elsewhere, in this case LDAP/AD. 

This change provides separate wrappers, 'http_basic', which maintains current functionality, and 'http_basic_autoregister' which creates a new account if one is not found for the given username.

**Comment by spladug** [comment]
Way cool! So glad to hear someone's using this pluggable thing :)

**Comment by grandpaslab** [comment]
Just updated this. Should not check password if using http_basic_autoregister. Passwords managed elsewhere.  

Probably http_basic should follow this pattern as well, but I'm not gonna mess with existing functionality.

**Comment by spladug** [comment]
Thanks for your contribution! I've merged it as 1b6df45fa121aba1ffa438f74cd9e16c7afa3922 with some minor tweaks.  I've also taken the opportunity to pull the authentication provider into the modern provider system which should be a bit more flexible in the future. Please let me know your reddit username if you'd like an open sourcerer trophy.

**Comment by grandpaslab** [comment]
Woohoo!  Thanks for this. Reddit username = github username = grandpaslab.

**Pull request closed without merging**
