### PR TITLE
Add width to oEmbed response (closes #1471)

### LINKED ISSUE #1471: Missing `width` property in oEmbed responses
The oEmbed response from reddit.com/oembed does not include a `width` property. Example response from [this oEmbed request](https://www.reddit.com/oembed?url=https://www.reddit.com/r/Showerthoughts/comments/2safxv/we_should_start_keeping_giraffes_a_secret_from/cno7zic):

```javascript
{
  "provider_url": "https://www.reddit.com/",
  "version": "1.0",
  "author_url": "https://www.reddit.com/user/h5f6jdh7b9vj0d3fhtnd",
  "title": "h5f6jdh7b9vj0d3fhtnd's comment from discussion \"We should start keeping giraffes a secret from young children. Imagine discovering giraffes exist when you were like 15. \"Woah! Check out that long necked horse!\"\"",
  "provider_name": "reddit",
  "type": "rich",
  "html": "<div class=\"reddit-embed\" data-embed-media=\"www.redditmedia.com\" data-embed-parent=\"false\" data-embed-live=\"false\" data-embed-created=\"2015-11-20T16:29:24.981644+00:00\"><a href=\"https://www.reddit.com/r/Showerthoughts/comments/2safxv/we_should_start_keeping_giraffes_a_secret_from/cno7zic\">Comment</a> from discussion <a href=\"https://www.reddit.com/r/Showerthoughts/comments/2safxv/we_should_start_keeping_giraffes_a_secret_from/\">h5f6jdh7b9vj0d3fhtnd's comment from discussion &quot;We should start keeping giraffes a secret from young children. Imagine discovering giraffes exist when you were like 15. &quot;Woah! Check out that long necked horse!&quot;&quot;</a>.</div><script async src=\"https://www.redditstatic.com/comment-embed.js\"></script>",
  "author_name": "h5f6jdh7b9vj0d3fhtnd"
}
```

The numeric `width` property is required as per section 2.3.4.4 of [the oEmbed spec](http://oembed.com/).

### PR DESCRIPTION
**Pull request by jkingsman**
Brings reddit into conformity with the [oEmbed spec](http://oembed.com/#section2) (see section 2.3.4.4 for `rich` type content).

### CODE REVIEW

**Comment by jkingsman** [comment]
This PR would close Issue #1471.

**Comment by umbrae** [comment]
:eyeglasses: @umbrae

**Comment by jkingsman** [comment]
Just wanted to check in on this, @umbrae

**Comment by bsimpson63** [comment]
Sorry, but this repository is no longer accepting pull requests. https://www.reddit.com/r/changelog/comments/6xfyfg/an_update_on_the_state_of_the_redditreddit_and/

**Pull request closed without merging**
