### PR TITLE
Fixes the overflow of AM conditions, turns them into paragraphs.

### PR DESCRIPTION
**Pull request by CrypticCraig**
AM condition text was overflowing to the right side of the page, this just fixes it so it all is shown nicely in normal paragraph form.

### CODE REVIEW

**Comment by Deimos** [comment]
Ah, this actually isn't the correct spot. That's only going to affect the textarea used on the edit page. From my quick playing around with it, you need to style the `<pre>` tag on the view page, with both:

    word-wrap: break-word;
    white-space: pre-wrap;

(Let me know if you just want me to do it instead of updating your pull req).

**Comment by CrypticCraig** [comment]
I believe I just did it the way you said, I had thought I specified pre, because I know when I was paying around with inspect element that's what I changed. If my new pull is wrong feel free to just do it on your own, I just figured I would give a go at a "Open Sorcerer" trophy :P

**Comment by CrypticCraig** [comment]
bump

**Comment by Deimos** [comment]
Sorry for the ridiculous delay on this, finally deployed: https://github.com/reddit/reddit/commit/ea163ace5c152bc76f05f79e63d7e5bc7f8ad994

**Pull request closed without merging**
