### PR TITLE
ImageResizingProvider: fix TypeError when calling resize_image

### PR DESCRIPTION
**Pull request by gg**
Using the default `no_op` image resizing provider, a TypeError occurs when I submit a link post via the API.

Here's a full traceback:

```
File '/usr/lib/python2.7/dist-packages/weberror/evalexception.py', line 431 in respond
  app_iter = self.application(environ, detect_start_response)
File '/home/vagrant/src/reddit/r2/r2/config/middleware.py', line 228 in __call__
  return self.app(environ, start_response)
File '/home/vagrant/src/reddit/r2/r2/config/middleware.py', line 286 in __call__
  return self.app(environ, start_response)
File '/home/vagrant/src/reddit/r2/r2/config/middleware.py', line 243 in __call__
  return self.app(environ, start_response)
File '/home/vagrant/src/reddit/r2/r2/config/middleware.py', line 258 in __call__
  return self.app(environ, start_response)
File '/home/vagrant/src/reddit/r2/r2/config/middleware.py', line 379 in __call__
  return self.app(environ, start_response)
File '/home/vagrant/src/reddit/r2/r2/config/middleware.py', line 405 in __call__
  return self.app(environ, custom_start_response)
File '/usr/lib/python2.7/dist-packages/routes/middleware.py', line 131 in __call__
  response = self.app(environ, start_response)
File '/usr/lib/python2.7/dist-packages/pylons/wsgiapp.py', line 103 in __call__
  response = self.dispatch(controller, environ, start_response)
File '/usr/lib/python2.7/dist-packages/pylons/wsgiapp.py', line 313 in dispatch
  return controller(environ, start_response)
File '/home/vagrant/src/reddit/r2/r2/lib/base.py', line 156 in __call__
  return WSGIController.__call__(self, environ, start_response)
File '/usr/lib/python2.7/dist-packages/pylons/controllers/core.py', line 214 in __call__
  response = self._dispatch_call()
File '/usr/lib/python2.7/dist-packages/pylons/controllers/core.py', line 164 in _dispatch_call
  response = self._inspect_call(func)
File '/usr/lib/python2.7/dist-packages/pylons/controllers/core.py', line 107 in _inspect_call
  result = self._perform_call(func, args)
File '/usr/lib/python2.7/dist-packages/pylons/controllers/core.py', line 57 in _perform_call
  return func(**args)
File '/home/vagrant/src/reddit/r2/r2/lib/validator/validator.py', line 210 in newfn
  return fn(self, *a, **kw)
File '/home/vagrant/src/reddit/r2/r2/controllers/front.py', line 536 in GET_comments
  return res.render()
File '/home/vagrant/src/reddit/r2/r2/lib/pages/pages.py', line 893 in render
  res = Templated.render(self, *a, **kw)
File 'wrapped.pyx', line 411 in r2.lib.wrapped.Templated.render (./r2/lib/wrapped.c:7228)
File 'wrapped.pyx', line 267 in r2.lib.wrapped.Templated._render (./r2/lib/wrapped.c:4738)
File 'wrapped.pyx', line 210 in r2.lib.wrapped.Templated.render_nocache (./r2/lib/wrapped.c:4136)
File '/home/vagrant/src/reddit/r2/r2/lib/jsontemplates.py', line 1103 in render
  return ObjectTemplate(thing.content().render() if thing else {})
File 'wrapped.pyx', line 411 in r2.lib.wrapped.Templated.render (./r2/lib/wrapped.c:7228)
File 'wrapped.pyx', line 267 in r2.lib.wrapped.Templated._render (./r2/lib/wrapped.c:4738)
File 'wrapped.pyx', line 210 in r2.lib.wrapped.Templated.render_nocache (./r2/lib/wrapped.c:4136)
File '/home/vagrant/src/reddit/r2/r2/lib/jsontemplates.py', line 1107 in render
  res = [t.render() for t in thing.stack if t] if thing else []
File 'wrapped.pyx', line 411 in r2.lib.wrapped.Templated.render (./r2/lib/wrapped.c:7228)
File 'wrapped.pyx', line 267 in r2.lib.wrapped.Templated._render (./r2/lib/wrapped.c:4738)
File 'wrapped.pyx', line 210 in r2.lib.wrapped.Templated.render_nocache (./r2/lib/wrapped.c:4136)
File '/home/vagrant/src/reddit/r2/r2/lib/jsontemplates.py', line 243 in render
  data = self.data(thing)))
File '/home/vagrant/src/reddit/r2/r2/lib/jsontemplates.py', line 239 in data
  return self.raw_data(thing)
File '/home/vagrant/src/reddit/r2/r2/lib/jsontemplates.py', line 201 in raw_data
  for k, v in attrs.iteritems())
File '/home/vagrant/src/reddit/r2/r2/lib/jsontemplates.py', line 201 in <genexpr>
  for k, v in attrs.iteritems())
File '/home/vagrant/src/reddit/r2/r2/lib/jsontemplates.py', line 1135 in thing_attr
  r = a.render()
File 'wrapped.pyx', line 411 in r2.lib.wrapped.Templated.render (./r2/lib/wrapped.c:7228)
File 'wrapped.pyx', line 267 in r2.lib.wrapped.Templated._render (./r2/lib/wrapped.c:4738)
File 'wrapped.pyx', line 210 in r2.lib.wrapped.Templated.render_nocache (./r2/lib/wrapped.c:4136)
File '/home/vagrant/src/reddit/r2/r2/lib/jsontemplates.py', line 116 in render
  data = cls.get_json(item)
File '/home/vagrant/src/reddit/r2/r2/lib/jsontemplates.py', line 866 in get_json
  images = generate_image_links(preview_object)
File '/home/vagrant/src/reddit/r2/r2/lib/jsontemplates.py', line 772 in generate_image_links
  max_ratio=PREVIEW_MAX_RATIO,
TypeError: resize_image() got an unexpected keyword argument 'file_type'
```

### CODE REVIEW

**Comment by bsimpson63** [comment]
Can you also update `ImageResizingProvider` and `UnsplashitImageResizingProvider`?

**Comment by gg** [comment]
> Can you also update ImageResizingProvider and UnsplashitImageResizingProvider?

Done. I also updated ImgixResizingProvider.

**Comment by rhysyngsun** [comment]
Hello, I'm also running into this and am curious if there's anything to be done to help it along?

**Comment by bsimpson63** [comment]
Sorry, but this repository is no longer accepting pull requests.

**Pull request closed without merging**
