### PR TITLE
Create Morris+Ganis

### PR DESCRIPTION
**Pull request by morrisgn-zz**
construction of paintings on canvas and objects with a cover of plywood on the top and also as a base of a plastic bag with a catalog facing a white side of a paper photograph

### CODE REVIEW

**Comment by yowar** [comment]
yo 012

**Comment by empyrical** [comment]
spladug I think you broke him

**Comment by empyrical** [comment]
srsly tho are you trying to use the reddit repo as some kind of weird art project or something?

**Comment by yowar** [comment]
At least political Art is concerned with human value of life...

**Pull request merged**
