### PR TITLE
JS parens/brace fix

### PR DESCRIPTION
**Pull request by strix-technica**
Fix broken JS syntax from commit 0c6546d58 which caused `uglyfyjs` to break `make static`.  

Also fix indentation.

@birakattack, you might want to double check that my edit is consistent with your intentions.

### CODE REVIEW

**Comment by birakattack** [comment]
:fish:

**Comment by strix-technica** [comment]
Cheers, @birakattack

**Comment by birakattack** [comment]
thanks for the fix 👍

**Comment by birakattack** [comment]
merged f56e810

**Pull request closed without merging**
