### PR TITLE
Add meta tag for AlienBlue in iOS

### PR DESCRIPTION
**Pull request by the-hobbes**
As per issue #1240, add a meta tag to support promotion of AlienBlue via Smart App Banners for iOS.

### CODE REVIEW

**Comment by english06** [comment]
Is there a way to add the "Navigational Context" as well?

https://developer.apple.com/library/prerelease/ios/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html

**Comment by the-hobbes** [comment]
Sure- just so I make sure I'm understanding correctly, we'd want to pass something like "https://www.reddit.com/#page=2" as the app-argument to the app so that the user can open the app at the same position she was in at the time of the smart banner click?

**Comment by english06** [comment]
Well even beyond that though. To submission pages, comment pages, messages, modmail. I think those 4 would cover most traffic. Going to specific content may be tough depending on Alien Blue design, but ideally just the general pages shouldn't.

**Comment by the-hobbes** [comment]
I'm passing the entire request url, with the intent that the iOS app will handle the navigation context routing.

**Comment by umbrae** [comment]
Thanks for the contribution, unfortunately we're not ready for this yet. We'll definitely be thinking about something like this at some point though.

**Pull request closed without merging**
