### PR TITLE
Expose a link's contest mode state in the API

### PR DESCRIPTION
**Pull request by 13steinj**
This will allow API clients to properly design a contest mode submission without having to slowly parse through all the comments.

### CODE REVIEW

**Comment by bb010g** [comment]
What's holding this up?

**Comment by 13steinj** [comment]
@bb010g nothing at all. Pull requests are slow. I've been waiting over a year on some of them, even small bug fixes.

**Comment by dkasper** [comment]
@13steinj thanks for this, resolved via https://github.com/reddit/reddit/commit/40b3436c4038d9564ce0fa1fd2c027d437703357

**Comment by 13steinj** [comment]
@dkasper ty

**Pull request closed without merging**
