### PR TITLE
Fixed magic number for SHA1 hash length

### PR DESCRIPTION
**Pull request by dustinpho**

### CODE REVIEW

**Comment by xiongchiamiov** [comment]
I would probably label it as the length of a [SHA-*1*](https://en.wikipedia.org/wiki/SHA-1) hash, since SHA-2 and SHA-3 have a variety of other lengths.

**Comment by dustinpho** [comment]
Got it. How does it look now?

**Comment by xiongchiamiov** [comment]
Reasonable to me.  I have absolutely no knowledge of that particular file (although this change is just simple C), so I'm going to hold off and let someone else approve it, though.

**Comment by spladug** [comment]
:fish: looks good! thanks :)

**Comment by bsimpson63** [comment]
Depoyed as e3431123abffea81c0e30304c23a95f97051082e.

Thanks for your contribution and sorry it took so long to get it merged. What's your reddit username so I can give you a trophy?

**Comment by dustinpho** [comment]
'dpho' is my reddit username.

**Pull request closed without merging**
