### PR TITLE
Add "archived" CSS class to post if not votable

### PR DESCRIPTION
**Pull request by andytuba**
www.reddit.com complement to 4a9d45a878cceb27c01f67eda658c72f2579f298

If a post cannot be voted upon, then render it as `<div class="thing ... archived">` in post listings or `<body class="single-page ... archived">` on its single-page view.

Subreddit stylesheets, user stylesheets, and browser extensions can take advantage of this by hiding unusable features such as up/down vote buttons or adding warning banners/tooltips.

---

This is untested, so I hope I put enough things in the right places and no things in the wrong ones.

### CODE REVIEW

**Comment by andytuba** [comment]
@largenocream also suggests reverting link.html and adding to printable.html:

    <%def name="thing_css_rowclass(what)">
      <%
        rowstyle = getattr(what, "rowstyle", "")
    
        if what.show_spam:
          ...

    +   if not getattr(thing, "votable", True):
    +     rowclass += "archived"

Thoughts?

**Comment by JordanMilne** [comment]
^`"Certain parties" == me`

**Comment by bsimpson63** [comment]
Adding that to printable.html would add the class to a bunch of things we probably don't want.

Another way to go would be to flip the logic use the `votable` attribute and then in printable add `" votable"` to the rowclass. This way comments would get the attribute also.

**Comment by bsimpson63** [comment]
bump

**Comment by andytuba** [comment]
@bsimpson63 Your "add votable to rowclass in printable" suggestion sounds good.  I'll update and rebase next week.

**Comment by kjoconnor** [comment]
Closing this for now just to clean up. Please feel free to reopen if you want to continue with this!

**Pull request closed without merging**
