### PR TITLE
Update subreddit ban message

### PR DESCRIPTION
**Pull request by Umdlye**

### CODE REVIEW

**Comment by 13steinj** [comment]
I'm not one to actually mean anything, but [bsimpson said the same thing](https://github.com/reddit/reddit/pull/1293#discussion_r44839135) when someone else's lines were too long; so the changed lines are too long (> 79 chars), you may just want to reformat a little to fit the constraints.

**Comment by Umdlye** [comment]
@13steinj There we go. I suck at this >.<

**Comment by 13steinj** [comment]
@Umdlye :/ :P :+1:

**Comment by umbrae** [comment]
:fish: Thanks! We'll add this.

**Comment by umbrae** [comment]
We're going to roll out verbiage really similar to this very soon. Thanks for it!

**Pull request closed without merging**
