### PR TITLE
Add username example to post sharing

### PR DESCRIPTION
**Pull request by allthefoxes**
From: https://www.reddit.com/r/ideasfortheadmins/comments/3br6bk/add_uusername_to_the_example_addresses_when/

### CODE REVIEW

**Comment by allthefoxes** [comment]
:eyeglasses: @madbook @bsimpson63

**Comment by allthefoxes** [comment]
On a second thought, it seems better to simply change the post sharing to be more clear about the username feature, but this could be a band-aid in the meantime.

**Comment by tdohz** [comment]
We actually deliberately removed the username example since (a) it was very infrequently used and (b) it can be confusing if you're a newer user and not yet acclimated to the /u/username syntax. It just didn't seem like the potential confusion was worth the tiny number of users who used this feature (especially since we still support it as a hidden feature).

> On a second thought, it seems better to simply change the post sharing to be more clear about the username feature

We _may_ add this back in. If we do decide to more explicitly support username sharing, it would be with UI that makes it very clear what's going on, probably as a separate option in the menu.

**Comment by allthefoxes** [comment]
:+1: user->user sharing should definitely still be support, IMO.

Thanks

**Pull request closed without merging**
