### PR TITLE
Change a few links to https

### PR DESCRIPTION
**Pull request by allthefoxes**
As requested here: https://www.reddit.com/r/bugs/comments/3abr9f/support_reddit_pacific_time_points_to_non_https/

### CODE REVIEW

**Comment by allthefoxes** [comment]
:eyeglasses: @madbook

**Comment by spladug** [comment]
:fish: thanks!

**Comment by spladug** [comment]
Merged (as ecf032e378e332803d548d1f90cf8dca106adb3a) and deployed to production. Thanks again!

**Comment by allthefoxes** [comment]
:+1:

**Pull request closed without merging**
