### PR TITLE
Add vid.me to case_sensitive_domains (closes #1342)

### LINKED ISSUE #1342: "Other Discussions" locator and repost-detector is case-insensitive for domain 'vid.me'
Example:

http://www.reddit.com/r/cats/duplicates/3aphna/ginger_purring_while_eating_her_favorite/

I believe the fix should just be including vid.me in the *case_sensitive_domains* token in the [example.ini](https://github.com/reddit/reddit/edit/master/r2/example.ini), but that file is autogenerated apparently and I shouldn't be editing it directly.

### PR DESCRIPTION
**Pull request by jkingsman**
Closes #1342.

### CODE REVIEW

**Comment by Siddhartha90** [comment]
:shipit: Thanks Jack.

**Comment by umbrae** [comment]
:fish: thanks

**Comment by jbboehr** [comment]
Would be nice to get this fixed - we're getting a lot of user complaints from the widget.

**Comment by jkingsman** [comment]
AFAIK this is ready to be reviewed and merged; pretty easy change.

**Comment by 13steinj** [comment]
The fish means it has been reviewed, I don't know why the actual merging didn't happen.

**Comment by mandlar** [comment]
Any update to this? Looks like it has been nearly a year?

**Comment by jkingsman** [comment]
@umbrae, any way we can get this merged?

**Comment by bsimpson63** [comment]
Sorry, but this repository is no longer accepting pull requests. https://www.reddit.com/r/changelog/comments/6xfyfg/an_update_on_the_state_of_the_redditreddit_and/

**Comment by mandlar** [comment]
Well that's a shame

**Pull request closed without merging**
