### PR TITLE
Add message to be used for when a subreddit is set to private.

### PR DESCRIPTION
**Pull request by justcool393**
IdeasForTheAdmins post: https://www.reddit.com/r/ideasfortheadmins/comments/3dgtar/have_a_separate_this_subreddit_is_private_message/

Username on reddit is same as here. Have tested this on a reddit instance and works fine.

### CODE REVIEW

**Comment by bsimpson63** [comment]
This looks great, but I thought you were just going to reword the description of the existing field to include something like "users will see this if your subreddit is private"?

**Comment by justcool393** [comment]
Oh, I got confused. I can do that and submit as a different pull request if you want.

**Comment by bsimpson63** [comment]
Please do.

This code looks good and correct, but I think for now it's better to not add an additional field.

**Comment by justcool393** [comment]
Now in #1369

**Pull request closed without merging**
