### PR TITLE
Added background-position-x and background-position-y to cssfilter

### PR DESCRIPTION
**Pull request by cmcarey**
See http://snook.ca/archives/html_and_css/background-position-x-y for exact details, but in short
- simplifies animation
- optimize sprites

### CODE REVIEW

**Comment by dt1973** [comment]
http://lists.w3.org/Archives/Public/www-style/2014Apr/0188.html

> RESOLVED: background-position-x/-y, background-repeat-x/-y approved for level 4 of backgrounds and borders.

from http://stackoverflow.com/questions/9653685/is-background-position-x-background-position-y-a-standard-w3c-css-property

Other:

- https://bugzilla.mozilla.org/show_bug.cgi?id=550426
- https://github.com/liuxuanzy/jquery-backgroundfix

**Comment by spladug** [comment]
:eyeglasses: @spladug

(I'm [taking this on for merging](https://github.com/reddit/reddit/wiki/The-Code-Salon))

**Comment by spladug** [comment]
Hi there, thanks for your patch! I've merged it as e2ecdc903a15f1bef73a0e947653c82842d16e2f. Please let me know your reddit username if you'd like an open sourcerer trophy.

**Comment by cmcarey** [comment]
Awesome, thanks!

I'm /u/Nouv.  Cheers :-)

**Comment by AndreasBackx** [comment]
Damn, I shouldn't have deleted my comment. No trophy for me.

**Pull request closed without merging**
