### PR TITLE
Add CSS mask and mask-border properties to filter

### PR DESCRIPTION
**Pull request by ethaksus**
Allow use of the mask property to allow raster-based masking of elements and borders.

### CODE REVIEW

**Comment by spladug** [comment]
:eyeglasses: @spladug (marking this for me to take a look at)

**Comment by ethaksus** [comment]
just checking in on this, I didn't need to do anything did I? I noticed that all the other PR's have that Travis thing run on them, but honestly not too sure how to do that myself

**Comment by 13steinj** [comment]
@ethaksus travis just ensures that tests will pass,  but that was implemented after your pr. The build will fail anyway, see #1646

**Comment by spladug** [comment]
Thanks for the contribution and apologies for the delay. This is deployed to production now!

b66145a980b90c282bdd9875eef7f77ad856f65b

**Pull request closed without merging**
