### PR TITLE
adjust maxlength html input attr for username

### PR DESCRIPTION
**Pull request by francis-liberty**
in sync with MAX_USERNAME_LENGTH in validator.py.
I checked templates folder, loginformwide.html and login.html is correctly '20'. No other mistakes found.

refer to inactive issue #1222 .

### CODE REVIEW

**Comment by bsimpson63** [comment]
Looks like password.html has a name input as well.

**Comment by francis-liberty** [comment]
Yeah, it has, but it didn't have maxLength before. I've added it now anyway.

**Comment by bsimpson63** [comment]
:fish: thanks, I'll get this merged.

**Comment by bsimpson63** [comment]
Merged as f72b11aae8651653bbbe295d86694b198ecc7000.

**Comment by bsimpson63** [comment]
Thanks for this contribution.

If you tell me your reddit username I can get you a trophy.

**Pull request closed without merging**
